# Generated by Django 5.0.6 on 2024-07-06 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='userId',
            new_name='orgId',
        ),
    ]
